version: '3'

services:
  gatewaydb:
    image: postgres
    ports:
      - "5435:80"
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - gatewaydb